stages:
    - build
    - publish
    - build-artifact
    - publish-utils

default:
    image: docker:latest
    before_script: |
        DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME/main/latest}
        if [ ! -z `command -v docker` ]; then
            echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_URL" ]; then echo -n $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_URL; fi
        fi
    after_script: |
        if [ ! -z `command -v docker` ]; then
            docker logout $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_URL" ]; then docker logout $DOCKER_REGISTRY_URL; fi
        fi

build:
    stage: build
    script:
        - docker build . --pull --build-arg COMMIT_SHA=$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
        - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    only:
        - branches
        - tags

publish:
    stage: publish
    script:
        - docker pull $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
        - docker tag $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG $DOCKER_REGISTRY_URL/$CI_PROJECT_NAME:$DOCKER_IMAGE_TAG
        - docker push $DOCKER_REGISTRY_URL/$CI_PROJECT_NAME:$DOCKER_IMAGE_TAG
    only:
        - main
        - tags

build-artifact:
    stage: build-artifact
    script:
        - (if [ ! -d flux-docker-gitlab-build-artifact ]; then mkdir -p flux-docker-gitlab-build-artifact && cd flux-docker-gitlab-build-artifact && wget -O - https://github.com/fluxfw/flux-docker-gitlab-build-artifact/releases/download/v2022-07-12-1/flux-docker-gitlab-build-artifact-v2022-07-12-1-build.tar.gz | tar -xz --strip-components=1; fi)
        - flux-docker-gitlab-build-artifact/bin/create-gitlab-artifact-from-docker-build.sh $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG /$CI_PROJECT_NAME build.tar.gz
    cache:
        key: build-artifact
        paths:
            - flux-docker-gitlab-build-artifact
    artifacts:
        paths:
            - build.tar.gz
        expire_in: 5 minutes
    only:
        - /^v[0-9-]+$/

publish-utils:
    stage: publish-utils
    image: php:cli-alpine
    script:
        - (if [ ! -d flux-publish-utils ]; then mkdir -p flux-publish-utils && cd flux-publish-utils && wget -O - https://github.com/fluxfw/flux-publish-utils/releases/download/v2022-07-12-1/flux-publish-utils-v2022-07-12-1-build.tar.gz | tar -xz --strip-components=1; fi)
        - if [ -n "$CI_COMMIT_TAG" ]; then flux-publish-utils/bin/upload-release-asset.php build.tar.gz $CI_PROJECT_NAME-$DOCKER_IMAGE_TAG-build.tar.gz; else flux-publish-utils/bin/publish-utils.php; fi
    cache:
        key: publish-utils
        paths:
            - flux-publish-utils
    only:
        - main
        - /^v[0-9-]+$/
